// Passphrase
const passphrase = 'base64:IES06ldztmFbjoPQnUvnMrUiZrJLMPi8GbxxhqSTKLQ='

const baseDev = 'https://tendero-core.herokuapp.com/api/'
const baseProd = 'https://tendero-core.herokuapp.com/api/'

const production = {
  login: `${baseProd}auth/login`,
  logout: `${baseProd}auth/logout`,
  refresh: `${baseProd}auth/refresh`,
  reset: `${baseProd}auth/reset`,
  currentUser: `${baseProd}auth/me`,
  companies: `${baseProd}companies`,
  companies_options: `${baseProd}companies-options`,
  countries: `${baseProd}countries`,
  countries_options: `${baseProd}countries-options`,
  currencies: `${baseProd}currencies`,
  currencies_options: `${baseProd}currencies-options`,
  users: `${baseProd}users`,
  stores: `${baseProd}stores`,
  stores_options: `${baseProd}stores-options`,
  storeType: `${baseProd}store-types`,
  storeType_options: `${baseProd}store-types-options`,
  storeChain: `${baseProd}store-chains`,
  storeChain_options: `${baseProd}store-chains-options`,
  storeFlag: `${baseProd}store-flags`,
  storeFlag_options: `${baseProd}store-flags-options`,
  Location: `${baseProd}location-types`,
  Location_options: `${baseProd}location-types-options`,
  storeFormat: `${baseProd}store-formats`,
  storeFormat_options: `${baseProd}store-formats-options`,
  socioeconomicLevel: `${baseProd}socioeconomic-levels`,
  socioeconomicLevel_options: `${baseProd}socioeconomic-levels-options`,
  states: `${baseProd}states`,
  states_options: `${baseProd}states-options`,
  Zones: `${baseProd}zones`,
  Zones_options: `${baseProd}zones-options`,
  Municipality: `${baseProd}municipalities`,
  Municipality_options: `${baseProd}municipalities-options`,
  Region: `${baseProd}regions`,
  Client: `${baseProd}clients`,
  Client_options: `${baseProd}clients-options`,
  Makers: `${baseProd}makers`,
  Uoms: `${baseProd}uoms`,
  Uoms_options: `${baseProd}uoms-options`,
  Brands: `${baseProd}brands`,
  Brands_options: `${baseProd}brands-options`,
  Providers: `${baseProd}providers`,
  Providers_options: `${baseProd}providers-options`,
  ProductDepartament: `${baseProd}product-departments`,
  ProductCategory: `${baseProd}product-categories`,
  ProductCategory_options: `${baseProd}product-categories-options`,
  ProductSubCategory: `${baseProd}product-subcategories`,
  ProductSubCategory_options: `${baseProd}product-subcategories-options`,
  products: `${baseProd}products`,
  products_options: `${baseProd}products-options`,
  productCategories: `${baseProd}product-categories`,
  productSubCategories: `${baseProd}product-subcategories`,
  brands: `${baseProd}brands`,
  uoms: `${baseProd}uoms`,
  locationType: `${baseProd}location-types`,
  paymentMethod: `${baseProd}payment-methods`,
  paymentMethod_options: `${baseProd}payment-methods-options`,
  Turns: `${baseProd}turns`,
  Turns_options: `${baseProd}turns-options`,
  Presentations: `${baseProd}presentations`,
  Presentations_options: `${baseProd}presentations-options`,
  Skus: `${baseProd}presentation-skus`,
  Combos: `${baseProd}presentation-combos`,
  permissions: `${baseProd}permissions`,
  userPermissions: userId => `${baseProd}users/${userId}/permissions`,
  transfers: `${baseProd}transfers`,
  counts: `${baseProd}stock-counts`,
  purchases: `${baseProd}purchases`,
  inventory: `${baseProd}stocks`,
  adjustments: `${baseProd}adjustments`,
  roles: `${baseProd}roles-options`,
  deposits: `${baseProd}deposits`,
  storeTurns: `${baseProd}store-turns`,
  sells: `${baseProd}sells`,
  sellsOffline: `${baseProd}sells-offline`,
  sellPayments: `${baseProd}sell-payments`,
  cashAdjustment: `${baseProd}cash-adjustments`,
  storesCash: `${baseProd}stores-cash`,
}

const develop = {
  login: `${baseDev}auth/login`,
  logout: `${baseDev}auth/logout`,
  refresh: `${baseDev}auth/refresh`,
  reset: `${baseDev}auth/reset`,
  currentUser: `${baseDev}auth/me`,
  companies: `${baseDev}companies`,
  companies_options: `${baseDev}companies-options`,
  countries: `${baseDev}countries`,
  countries_options: `${baseDev}countries-options`,
  currencies: `${baseDev}currencies`,
  currencies_options: `${baseDev}currencies-options`,
  users: `${baseDev}users`,
  stores: `${baseDev}stores`,
  stores_options: `${baseDev}stores-options`,
  storeType: `${baseDev}store-types`,
  storeType_options: `${baseDev}store-types-options`,
  storeChain: `${baseDev}store-chains`,
  storeChain_options: `${baseDev}store-chains-options`,
  storeFlag: `${baseDev}store-flags`,
  storeFlag_options: `${baseDev}store-flags-options`,
  Location: `${baseDev}location-types`,
  Location_options: `${baseDev}location-types-options`,
  storeFormat: `${baseDev}store-formats`,
  storeFormat_options: `${baseDev}store-formats-options`,
  socioeconomicLevel: `${baseDev}socioeconomic-levels`,
  socioeconomicLevel_options: `${baseDev}socioeconomic-levels-options`,
  states: `${baseDev}states`,
  states_options: `${baseDev}states-options`,
  Zones: `${baseDev}zones`,
  Zones_options: `${baseDev}zones-options`,
  Municipality: `${baseDev}municipalities`,
  Municipality_options: `${baseDev}municipalities-options`,
  Region: `${baseDev}regions`,
  Client: `${baseDev}clients`,
  Client_options: `${baseDev}clients-options`,
  Makers: `${baseDev}makers`,
  Uoms: `${baseDev}uoms`,
  Uoms_options: `${baseDev}uoms-options`,
  Brands: `${baseDev}brands`,
  Brands_options: `${baseDev}brands-options`,
  Providers: `${baseDev}providers`,
  Providers_options: `${baseDev}providers-options`,
  ProductDepartament: `${baseDev}product-departments`,
  ProductCategory: `${baseDev}product-categories`,
  ProductCategory_options: `${baseDev}product-categories-options`,
  ProductSubCategory: `${baseDev}product-subcategories`,
  ProductSubCategory_options: `${baseDev}product-subcategories-options`,
  products: `${baseDev}products`,
  products_options: `${baseDev}products-options`,
  productCategories: `${baseDev}product-categories`,
  productSubCategories: `${baseDev}product-subcategories`,
  brands: `${baseDev}brands`,
  uoms: `${baseDev}uoms`,
  locationType: `${baseDev}location-types`,
  paymentMethod: `${baseDev}payment-methods`,
  paymentMethod_options: `${baseDev}payment-methods-options`,
  Turns: `${baseDev}turns`,
  Turns_options: `${baseDev}turns-options`,
  Presentations: `${baseDev}presentations`,
  Presentations_options: `${baseDev}presentations-options`,
  Skus: `${baseDev}presentation-skus`,
  Combos: `${baseDev}presentation-combos`,
  permissions: `${baseDev}permissions`,
  userPermissions: userId => `${baseDev}users/${userId}/permissions`,
  transfers: `${baseDev}transfers`,
  counts: `${baseDev}stock-counts`,
  purchases: `${baseDev}purchases`,
  inventory: `${baseDev}stocks`,
  adjustments: `${baseDev}adjustments`,
  roles: `${baseDev}roles-options`,
  deposits: `${baseDev}deposits`,
  storeTurns: `${baseDev}store-turns`,
  sells: `${baseDev}sells`,
  sellsOffline: `${baseDev}sells-offline`,
  sellPayments: `${baseDev}sell-payments`,
  cashAdjustment: `${baseDev}cash-adjustments`,
  storesCash: `${baseDev}stores-cash`,
}

const environment = env => {
  switch (env) {
    case 'production':
      return production
    default:
      return develop
  }
}

module.exports = {
  stage: environment('develop'),
  passphrase,
}
